name: Furniture Store CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Determine flavor based on tag
        run: |
          tag=$CI_COMMIT_TAG
          build_type='release'
          if [[ $tag == 'uat'* ]]; then
            flavor='uat'
          else
            flavor='prd'
          fi
          echo "Flavor: $flavor"
          echo "Build Type: $build_type"
          echo "::set-output name=flavor::$flavor"
          echo "::set-output name=build_type::$build_type"

      - name: Build APK
        run: |
          flavor=$(/bin/bash -c "echo ${{ steps.determine-flavor.outputs.flavor }}")
          build_type=$(/bin/bash -c "echo ${{ steps.determine-flavor.outputs.build_type }}")
          ./gradlew "assemble${flavor}${build_type}"

      - name: Copy APK
        run: |
          flavor=$(/bin/bash -c "echo ${{ steps.determine-flavor.outputs.flavor }}")
          build_type=$(/bin/bash -c "echo ${{ steps.determine-flavor.outputs.build_type }}")
          apkDir="app/build/outputs/apk/${flavor}/${build_type}"
          apkMetaFile="$apkDir/output-metadata.json"
          apkFile=$(cat $apkMetaFile | jq -r '.elements[0].outputFile')
          cp "${apkDir}/${apkFile}" "furniture-store.apk"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: furniture-store
          path: furniture-store.apk